---
title: "Lab05"
author: "Daniel Kang"
date: "9/29/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(ggplot2)
github <- "https://github.com/ucb-stat133/stat133-fall-2017/raw/master/"
csv <- "data/nba2017-players.csv"
download.file(url = paste0(github, csv), destfile = 'nba2017-players.csv')
getwd()
dat <- read.csv('nba2017-players.csv', stringsAsFactors = FALSE)
str(dat)
```

#Filtering, slicing, and selecting
```{r}
#use slice() to subset the data by selecting the first 5 rows.
first5rows <- slice( dat, 1:5)
#use filter() to subset those players with height less than 70 inches tall.
hless70 <- filter(dat, height < 70 )
dat <- read.csv('nba2017-players.csv', stringsAsFactors = FALSE)

# with "readr" read_csv()
dat <- read_csv('nba2017-players.csv')
```


```{r}
#using the data frame gsw, add a new variable product with the product of height and weight.

#create a new data frame gsw3, by adding columns log_height and log_weight with the log transformations of height and weight.
log_height <- log(dat$height)
log_weight <- log(dat$weight)
mutate(dat, log_height, log_weight)
gsw3 <- data.frame(log_height, log_weight )
#use the original data frame to filter() and arrange() those players with height less than 71 inches tall, in increasing order.

summarise(dat, avg_salary = mean(salary))
#display the name, team, and salary, of the top-5 highest paid players
```